//
//  SecondAddRouter.swift
//  Camilo
//
//  Created by Juan C. Rodriguez B on 12/11/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SecondAddRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol SecondAddDataPassing
{
  var dataStore: SecondAddDataStore? { get }
}

class SecondAddRouter: NSObject, SecondAddRoutingLogic, SecondAddDataPassing
{
  weak var viewController: SecondAddViewController?
  var dataStore: SecondAddDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: SecondAddViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: SecondAddDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
