//
//  SecondAddPresenter.swift
//  Camilo
//
//  Created by Juan C. Rodriguez B on 12/11/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SecondAddPresentationLogic
{
  func presentSomething(response: SecondAdd.Something.Response)
}

class SecondAddPresenter: SecondAddPresentationLogic
{
  weak var viewController: SecondAddDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: SecondAdd.Something.Response)
  {
    let viewModel = SecondAdd.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
