//
//  SecondAddViewController.swift
//  Camilo
//
//  Created by Juan C. Rodriguez B on 12/11/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SecondAddDisplayLogic: AnyObject
{
    func displaySomething(viewModel: SecondAdd.Something.ViewModel)
}

class SecondAddViewController: UIViewController, SecondAddDisplayLogic, UITableViewDelegate, UITableViewDataSource
{
    
    @IBOutlet weak var backBtn: UIButton!
    @IBOutlet weak var tableView1: UITableView!
    var acc = ["Nassfutter geben","Power Gassi","Neuen Fressnapf kaufen", "Für Hundeschule anmelden"]
    
    var  hora = ["Täglich um 09:00 und 19:00","TTäglich um 12:00 und 15:00","äglich um 5:00 und  22:00", ""]
    var interactor: SecondAddBusinessLogic?
    var router: (NSObjectProtocol & SecondAddRoutingLogic & SecondAddDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = SecondAddInteractor()
        let presenter = SecondAddPresenter()
        let router = SecondAddRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        doSomething()
        tableView1.register(UINib(nibName: "Actions", bundle: nil), forCellReuseIdentifier: "Actions")
        
        tableView1.delegate = self
        tableView1.dataSource = self
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func doSomething()
    {
        let request = SecondAdd.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: SecondAdd.Something.ViewModel)
    {
        //nameTextField.text = viewModel.name
    }
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        
        return acc.count
    }
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        
        let cell = tableView1.dequeueReusableCell(withIdentifier: "Actions", for: indexPath) as! Actions
        cell.addActions.text = acc[indexPath.row]
        
        
        
        
        return cell
    }
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        
        
        
        return 80
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        
        tableView.deselectRow(at: indexPath, animated: true)
        
        let vc = UIStoryboard.init(name: "Main", bundle: Bundle.main).instantiateViewController(withIdentifier: "ThirdViewController") as? ThirdViewController
        vc?.receive = acc[indexPath.row]
        vc?.titles.append(acc[indexPath.row])
        vc?.arr.append(acc[indexPath.row])
        self.navigationController?.pushViewController(vc!, animated: true)
        
    }
    
    @IBAction func onBackBtn(_ sender: Any) {
        
        let vc = UIStoryboard.init(name: "Main", bundle: Bundle.main).instantiateViewController(withIdentifier: "ThirdViewController") as? ThirdViewController
        self.navigationController?.pushViewController(vc!, animated: true)
    }
    
}
