//
//  SecondAddInteractor.swift
//  Camilo
//
//  Created by Juan C. Rodriguez B on 12/11/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SecondAddBusinessLogic
{
  func doSomething(request: SecondAdd.Something.Request)
}

protocol SecondAddDataStore
{
  //var name: String { get set }
}

class SecondAddInteractor: SecondAddBusinessLogic, SecondAddDataStore
{
  var presenter: SecondAddPresentationLogic?
  var worker: SecondAddWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SecondAdd.Something.Request)
  {
    worker = SecondAddWorker()
    worker?.doSomeWork()
    
    let response = SecondAdd.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
