//
//  SecondAllInteractor.swift
//  Camilo
//
//  Created by Juan C. Rodriguez B on 12/11/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SecondAllBusinessLogic
{
  func doSomething(request: SecondAll.Something.Request)
}

protocol SecondAllDataStore
{
  //var name: String { get set }
}

class SecondAllInteractor: SecondAllBusinessLogic, SecondAllDataStore
{
  var presenter: SecondAllPresentationLogic?
  var worker: SecondAllWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SecondAll.Something.Request)
  {
    worker = SecondAllWorker()
    worker?.doSomeWork()
    
    let response = SecondAll.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
