//
//  SecondAllViewController.swift
//  Camilo
//
//  Created by Juan C. Rodriguez B on 12/11/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SecondAllDisplayLogic: AnyObject
{
    func displaySomething(viewModel: SecondAll.Something.ViewModel)
}

class SecondAllViewController: UIViewController, SecondAllDisplayLogic, UITableViewDelegate, UITableViewDataSource
{
    @IBOutlet weak var backTn: UIButton!
    @IBOutlet weak var tableView1: UITableView!
    var interactor: SecondAllBusinessLogic?
    var router: (NSObjectProtocol & SecondAllRoutingLogic & SecondAllDataPassing)?
    
    // MARK: Object lifecycle
    var acc = ["Nassfutter geben","Power Gassi","Neuen Fressnapf kaufen", "Für Hundeschule anmelden","Reisen","Essen","Spaziergang","Geh zum Tierarzt"]
    
    var  hora = ["Täglich um 09:00 und 19:00","TTäglich um 12:00 und 15:00","äglich um 5:00 und  22:00", "&:00 und !3:00","10:00 und 19:00","4:00 und 16:00","9:00 und 20:00","12:00 und 22:00"]
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = SecondAllInteractor()
        let presenter = SecondAllPresenter()
        let router = SecondAllRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        doSomething()
        tableView1.register(UINib(nibName: "SecondTableViewCell", bundle: nil), forCellReuseIdentifier: "SecondTableViewCell")
        tableView1.dataSource = self
        tableView1.delegate = self
        tableView1.layer.cornerRadius = 20
        backTn.layer.cornerRadius = 17.5
        
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func doSomething()
    {
        let request = SecondAll.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: SecondAll.Something.ViewModel)
    {
        //nameTextField.text = viewModel.name
    }
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        
        return acc.count
    }
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        
        let cell = tableView.dequeueReusableCell(withIdentifier: "SecondTableViewCell", for: indexPath) as? SecondTableViewCell
        cell?.lblTitle.text = acc[indexPath.row]
        cell?.descLbl.text = hora[indexPath.row]
        
        
        return cell!
    }
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        
        
        
        return 60
    }
    
    
    
    @IBAction func onBackBtn(_ sender: Any) {
        let vc = UIStoryboard.init(name: "Main", bundle: Bundle.main).instantiateViewController(withIdentifier: "ThirdViewController") as? ThirdViewController
        self.navigationController?.pushViewController(vc!, animated: true)
    }
    
}
