//
//  ThirdViewController.swift
//  Camilo
//
//  Created by Juan C. Rodriguez B on 11/11/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import DropDown
protocol ThirdDisplayLogic: AnyObject
{
    func displaySomething(viewModel: Third.Something.ViewModel)
}

class ThirdViewController: UIViewController, ThirdDisplayLogic
{
    var interactor: ThirdBusinessLogic?
    var router: (NSObjectProtocol & ThirdRoutingLogic & ThirdDataPassing)?
    
    
    @IBOutlet weak var addBtn: UIButton!
    @IBOutlet weak var tableView: UITableView!
    @IBOutlet weak var collectionView: UICollectionView!
    
    @IBOutlet weak var backBtn: UIButton!
    let item = ["dog_2", "dog_1"]
    let namePet = [ "Black Beauty","Lucky"]
    var titles = ["Nassfutter geben","Power Gassi","Neuen Fressnapf kaufen","Für Hundeschule anmelden", " "]
    var cellWidth = UIScreen.main.bounds.width / 3.5
    var arr = [""]
    var receive:String?
    let dropDown = DropDown()
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = ThirdInteractor()
        let presenter = ThirdPresenter()
        let router = ThirdRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        doSomething()
        collectionView.dataSource = self
        collectionView.delegate = self
        collectionView.register(UINib(nibName: "ThirdCellCollectionViewCell", bundle: nil), forCellWithReuseIdentifier: "ThirdCellCollectionViewCell")
        
        tableView.register(UINib(nibName: "SecondTableViewCell", bundle: nil), forCellReuseIdentifier: "SecondTableViewCell")
        tableView.dataSource = self
        tableView.delegate = self
        tableView.layer.cornerRadius = 20
        backBtn.layer.cornerRadius = 17.5
        addBtn.layer.cornerRadius = 20.5
        
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func doSomething()
    {
        let request = Third.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: Third.Something.ViewModel)
    {
        //nameTextField.text = viewModel.name
    }
    func setupGenderDropDown(cell: SecondTableViewCell) {
        dropDown.dataSource = ["Täglich um 09:00 und 19:00", "Täglich um 12:00 und 15:00", "Täglich um 5:00 und  22:00"]//4
        dropDown.anchorView = cell.descLbl //5
        dropDown.bottomOffset = CGPoint(x: 0, y: (cell.frame.size.height)) //6
        dropDown.show() //7
        dropDown.selectionAction = { [weak self] (index: Int, item: String) in //8
            guard let _ = self else { return }
            //sender.setTitle(item, for: .normal) //9
            cell.descLbl.text = item
        }
        
    }
    func powerGassi(cell: SecondTableViewCell) {
        dropDown.dataSource = ["Jeden Di. und Do. um 16:00", "Jeden Mo., Mi. und Sa. um 9:00 Uhr", "Jeden Fre. und Son. um 18:00 Uhr", "Jeden Mo. und Sa. um 11:00 Uhr"]//4
        dropDown.anchorView = cell.descLbl //5
        dropDown.bottomOffset = CGPoint(x: 0, y: (cell.frame.size.height)) //6
        dropDown.show() //7
        dropDown.selectionAction = { [weak self] (index: Int, item: String) in //8
            guard let _ = self else { return }
            //sender.setTitle(item, for: .normal) //9
            cell.descLbl.text = item
        }
        
    }
    func Neuen (cell: SecondTableViewCell) {
        dropDown.dataSource = ["Fressnapf XXL München"]//4
        dropDown.anchorView = cell.descLbl //5
        dropDown.bottomOffset = CGPoint(x: 0, y: (cell.frame.size.height)) //6
        dropDown.show() //7
        dropDown.selectionAction = { [weak self] (index: Int, item: String) in //8
            guard let _ = self else { return }
            //sender.setTitle(item, for: .normal) //9
            cell.descLbl.text = item
            cell.cirImg.image = UIImage(named: "new_moon")
            
        }
        
    }
    func Fur (cell: SecondTableViewCell) {
        dropDown.dataSource = ["Für Hundeschule anmelden"]//4
        dropDown.anchorView = cell.descLbl //5
        dropDown.bottomOffset = CGPoint(x: 0, y: (cell.frame.size.height)) //6
        dropDown.show() //7
        dropDown.selectionAction = { [weak self] (index: Int, item: String) in //8
            guard let _ = self else { return }
            //sender.setTitle(item, for: .normal) //9
            cell.descLbl.text = item
            cell.cirImg.image = UIImage(named: "new_moon")
            
        }
        
    }
    
    @IBAction func onBtnBack(_ sender: Any) {
        let story = self.storyboard?.instantiateViewController(withIdentifier: "FirstViewController")  as! FirstViewController
        self.navigationController?.pushViewController(story, animated: true)
        
    }
    @IBAction func onAddBtn(_ sender: Any) {
        let story = self.storyboard?.instantiateViewController(withIdentifier: "SecondAddViewController")  as! SecondAddViewController
        self.navigationController?.pushViewController(story, animated: true)
    }
    
    
    
    
}

extension ThirdViewController: UICollectionViewDataSource{
    
    func numberOfSections(in collectionView: UICollectionView) -> Int {
        return 1
    }
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return item.count
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let imagename = item[indexPath.item]
        var cell = collectionView.dequeueReusableCell(withReuseIdentifier: "ThirdCellCollectionViewCell", for: indexPath) as? ThirdCellCollectionViewCell
        cell?.backgroundColor = .lightGray
        cell?.imgCV.image = UIImage(named: imagename)
        cell?.nameLbl.text = namePet[indexPath.item]
        return cell!
    }
    
    
    
    
}

extension ThirdViewController: UICollectionViewDelegate{
    
    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        print("\(indexPath.section) => \(indexPath.row)")
        if (indexPath.row == 1) {
            item[indexPath.row ]
            let story = self.storyboard?.instantiateViewController(withIdentifier: "SecondViewController")  as! SecondViewController
            self.navigationController?.pushViewController(story, animated: true)
        }
        
    }
}
extension ThirdViewController: UICollectionViewDelegateFlowLayout{
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
        if (indexPath.row == 1) {
            cellWidth = cellWidth - 35
            collectionView.alignmentRectInsets.bottom
            item[indexPath.row ]
        }
        if (indexPath.row == 0) {
            
            item[indexPath.row ]
        }
        return CGSize (width: cellWidth, height: cellWidth)
    }
    
}
extension ThirdViewController: UITableViewDelegate, UITableViewDataSource{
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return titles.count
    }
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 60
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "SecondTableViewCell", for: indexPath) as? SecondTableViewCell
        cell?.lblTitle.text = titles[indexPath.row]
        
        switch indexPath.row {
        case 0:
            cell?.arrowImg.image = UIImage(named: "down")
            cell?.cirImg.image = UIImage(named: "recycle")
            
            
            cell?.otDescLbl.isHidden = true
        case 1:
            cell?.arrowImg.image = UIImage(named: "down")
            cell?.cirImg.image = UIImage(named: "recycle")
            cell?.descLbl.text = "Jeden Di. und Do. um 16:00"
            cell?.otDescLbl.isHidden = true
        case 2:
            cell?.cirImg.image = UIImage(named: "circle")
            cell?.descLbl.text = "Fressnapf XXL München"
            cell?.otDescLbl.isHidden = true
        case 3:
            cell?.cirImg.image = UIImage(named: "circle")
            cell?.descLbl.isHidden = true
            cell?.otDescLbl.isHidden = true
        case 4:
            cell?.arrowImg.image = UIImage(named: "next")
            cell?.descLbl.isHidden = true
            cell?.otDescLbl.text = "Alle anzeigen"
        default:
            print("NO SE ENCONTRO TITULO")
        }
        return cell!
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)
        print(indexPath.row)
        let cell = self.tableView.dequeueReusableCell(withIdentifier: "SecondTableViewCell") as? SecondTableViewCell
        if (indexPath.row == 0){
            
            //sender.setTitle(item, for: .normal) //9
            guard let currentCell = tableView.cellForRow(at: indexPath) else { return }
            setupGenderDropDown(cell: currentCell as! SecondTableViewCell)
            
        }
        if (indexPath.row == 1){
            
            guard let currentCell = tableView.cellForRow(at: indexPath) else { return }
            powerGassi(cell: currentCell as! SecondTableViewCell)
            
            
        }
        if (indexPath.row == 2){
            
            guard let currentCell = tableView.cellForRow(at: indexPath) else { return }
            Neuen(cell: currentCell as! SecondTableViewCell)
            
            
        }
        if (indexPath.row == 3){
            
            guard let currentCell = tableView.cellForRow(at: indexPath) else { return }
            Fur(cell: currentCell as! SecondTableViewCell)
            
            
        }
        if (indexPath.row == 4){
            
            let vc = UIStoryboard.init(name: "Main", bundle: Bundle.main).instantiateViewController(withIdentifier: "SecondAllViewController") as? SecondAllViewController
            self.navigationController?.pushViewController(vc!, animated: true)
            
            
        }
        
    }
    
    
    
    
    
}
