//
//  ThirdInteractor.swift
//  Camilo
//
//  Created by Juan C. Rodriguez B on 11/11/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import DropDown

protocol ThirdBusinessLogic
{
  func doSomething(request: Third.Something.Request)
}

protocol ThirdDataStore
{
  //var name: String { get set }
}

class ThirdInteractor: ThirdBusinessLogic, ThirdDataStore
{
  var presenter: ThirdPresentationLogic?
  var worker: ThirdWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Third.Something.Request)
  {
    worker = ThirdWorker()
    worker?.doSomeWork()
    
    let response = Third.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
