//
//  ThirdPresenter.swift
//  Camilo
//
//  Created by Juan C. Rodriguez B on 11/11/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ThirdPresentationLogic
{
  func presentSomething(response: Third.Something.Response)
}

class ThirdPresenter: ThirdPresentationLogic
{
  weak var viewController: ThirdDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Third.Something.Response)
  {
    let viewModel = Third.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
