//
//  AllTaskInteractor.swift
//  Camilo
//
//  Created by Juan C. Rodriguez B on 12/11/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AllTaskBusinessLogic
{
  func doSomething(request: AllTask.Something.Request)
}

protocol AllTaskDataStore
{
  //var name: String { get set }
}

class AllTaskInteractor: AllTaskBusinessLogic, AllTaskDataStore
{
  var presenter: AllTaskPresentationLogic?
  var worker: AllTaskWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: AllTask.Something.Request)
  {
    worker = AllTaskWorker()
    worker?.doSomeWork()
    
    let response = AllTask.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
