//
//  AllTaskPresenter.swift
//  Camilo
//
//  Created by Juan C. Rodriguez B on 12/11/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AllTaskPresentationLogic
{
  func presentSomething(response: AllTask.Something.Response)
}

class AllTaskPresenter: AllTaskPresentationLogic
{
  weak var viewController: AllTaskDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: AllTask.Something.Response)
  {
    let viewModel = AllTask.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
