//
//  AddTaskPresenter.swift
//  Camilo
//
//  Created by Juan C. Rodriguez B on 11/11/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddTaskPresentationLogic
{
  func presentSomething(response: AddTask.Something.Response)
}

class AddTaskPresenter: AddTaskPresentationLogic
{
  weak var viewController: AddTaskDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: AddTask.Something.Response)
  {
    let viewModel = AddTask.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
